//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticleTbl()
        {
            this.sellFactors = new HashSet<sellFactor>();
            this.StorageTbls = new HashSet<StorageTbl>();
        }
    
        public int articleID { get; set; }
        public string articleCode { get; set; }
        public string articleName { get; set; }
        public string articleDesc { get; set; }
        public long articlePrice { get; set; }
        public System.DateTime articleExDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sellFactor> sellFactors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageTbl> StorageTbls { get; set; }
    }
}
