//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerTbl()
        {
            this.sellFactors = new HashSet<sellFactor>();
        }
    
        public int customerID { get; set; }
        public string customerName { get; set; }
        public string customerFamily { get; set; }
        public string customerFatherName { get; set; }
        public long customerNationalCode { get; set; }
        public string customerPhoneNumber { get; set; }
        public string customerAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sellFactor> sellFactors { get; set; }
    }
}
