//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainStorageTbl
    {
        public int mainstorageID { get; set; }
        public string articleCode { get; set; }
        public System.DateTime articleExDate { get; set; }
        public string operatorName { get; set; }
        public long articlePrice { get; set; }
        public System.DateTime setDate { get; set; }
        public int articleCount { get; set; }
    }
}
