//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class accauntingDBEntities : DbContext
    {
        public accauntingDBEntities()
            : base("name=accauntingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleTbl> ArticleTbls { get; set; }
        public virtual DbSet<CustomerTbl> CustomerTbls { get; set; }
        public virtual DbSet<mainStorageTbl> mainStorageTbls { get; set; }
        public virtual DbSet<RoleTbl> RoleTbls { get; set; }
        public virtual DbSet<sellFactor> sellFactors { get; set; }
        public virtual DbSet<StorageTbl> StorageTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userTbl> userTbls { get; set; }
    }
}
