//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellFactor
    {
        public int sellFactorId { get; set; }
        public string sellerPerson { get; set; }
        public int customerIdFK { get; set; }
        public string customerPhoneNumber { get; set; }
        public string customerAddress { get; set; }
        public int articleIdFK { get; set; }
        public string articleName { get; set; }
        public int articleCount { get; set; }
        public long articlePrice { get; set; }
        public long discount { get; set; }
        public long sellPrice { get; set; }
    
        public virtual ArticleTbl ArticleTbl { get; set; }
        public virtual CustomerTbl CustomerTbl { get; set; }
    }
}
